package review

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// WriteReviewArtifact writes the review as a Markdown file to runs/<run_id>/review.md.
func WriteReviewArtifact(artifactDir string, r *Review) (string, error) {
	artifactPath := filepath.Join(artifactDir, "review.md")

	var b strings.Builder

	b.WriteString("# Prizm Review\n\n")
	b.WriteString("## Run Info\n\n")
	b.WriteString(fmt.Sprintf("- **Run ID:** `%s`\n", r.RunID))
	b.WriteString(fmt.Sprintf("- **Correlation ID:** `%s`\n", r.CorrelationID))
	b.WriteString(fmt.Sprintf("- **Reviewer:** %s\n", r.Reviewer))
	b.WriteString(fmt.Sprintf("- **Reviewed at:** %s\n", r.CreatedAt.Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("- **Mutation Status:** %s\n", r.MutationStatus))
	b.WriteString(fmt.Sprintf("- **Validation Status:** %s\n", r.ValidationStatus))
	b.WriteString("\n")

	b.WriteString("## Summary\n\n")
	b.WriteString(r.Summary + "\n\n")

	if len(r.FilesChanged) > 0 {
		b.WriteString("## Files Changed\n\n")
		for _, f := range r.FilesChanged {
			b.WriteString(fmt.Sprintf("- `%s`\n", f))
		}
		b.WriteString("\n")
	}

	if len(r.ValidationResults) > 0 {
		b.WriteString("## Validation Results\n\n")
		b.WriteString("| Profile | Status | Exit Code | Duration |\n")
		b.WriteString("|---------|--------|-----------|----------|\n")
		for _, vr := range r.ValidationResults {
			b.WriteString(fmt.Sprintf("| %s | %s | %d | %dms |\n", vr.Profile, vr.Status, vr.ExitCode, vr.DurationMs))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Reviewer Notes\n\n")
	b.WriteString(r.ReviewerNotes + "\n\n")
	b.WriteString("*This review was generated deterministically from validation results and mutation metadata. No LLM was used.*\n\n")

	switch r.Recommendation {
	case RecommendationApproved:
		b.WriteString("✅ **Ready for human review.** All checks passed. Please review the changes manually before merging.\n\n")
	case RecommendationNeedsFix:
		b.WriteString("⚠️ **Needs fixes.** The reviewer identified issues that should be addressed before proceeding.\n\n")
	case RecommendationValidationFailed:
		b.WriteString("❌ **Validation failed.** One or more validation checks did not pass. Fix the issues and re-run validation.\n\n")
	case RecommendationNoMutation:
		b.WriteString("ℹ️ **No changes detected.** Nothing to review.\n\n")
	}

	b.WriteString("## Recommendation\n\n")
	b.WriteString(fmt.Sprintf("**%s**\n\n", r.Recommendation))

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("*Generated by %s on %s*\n", r.Reviewer, r.CreatedAt.Format(time.RFC3339)))

	if err := os.WriteFile(artifactPath, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("failed to write review artifact: %w", err)
	}

	return artifactPath, nil
}
