package autopatch

import (
	"context"
	"fmt"
	"regexp"
	"strings"
)

// pr.go adds the final step of self-patching: turn a validated patch into a real
// pull request. The PROpener is an interface so the branch/commit/push/PR
// orchestration is unit-testable with a mock, while the default implementation
// shells out to git + gh.

// PRRequest describes the PR to open from a validated worktree.
type PRRequest struct {
	Worktree   string
	Branch     string
	Title      string
	Body       string
	BaseBranch string
}

// PRResult is the outcome of opening a PR.
type PRResult struct {
	URL    string
	Branch string
}

// PROpener commits the worktree changes onto a branch and opens a PR.
type PROpener interface {
	OpenPR(ctx context.Context, req PRRequest) (PRResult, error)
}

// ghPROpener is the default PROpener: it branches, commits, pushes, and opens a
// PR with the GitHub CLI (`gh`). It runs in the autopatch worktree, so the parent
// repo is never touched directly.
type ghPROpener struct{}

var prURLPattern = regexp.MustCompile(`https?://\S+`)

func (ghPROpener) OpenPR(ctx context.Context, req PRRequest) (PRResult, error) {
	wt := req.Worktree
	if _, err := runCommand(ctx, wt, "", "git", "checkout", "-b", req.Branch); err != nil {
		return PRResult{}, fmt.Errorf("create branch: %w", err)
	}
	if _, err := runCommand(ctx, wt, "", "git", "add", "-A"); err != nil {
		return PRResult{Branch: req.Branch}, fmt.Errorf("git add: %w", err)
	}
	if _, err := runCommand(ctx, wt, "", "git", "commit", "-m", req.Title); err != nil {
		return PRResult{Branch: req.Branch}, fmt.Errorf("git commit: %w", err)
	}
	if _, err := runCommand(ctx, wt, "", "git", "push", "-u", "origin", req.Branch); err != nil {
		return PRResult{Branch: req.Branch}, fmt.Errorf("git push: %w", err)
	}
	args := []string{"pr", "create", "--title", req.Title, "--body", req.Body, "--head", req.Branch}
	if req.BaseBranch != "" {
		args = append(args, "--base", req.BaseBranch)
	}
	out, err := runCommand(ctx, wt, "", "gh", args...)
	if err != nil {
		return PRResult{Branch: req.Branch}, fmt.Errorf("gh pr create: %w", err)
	}
	return PRResult{URL: prURLPattern.FindString(out), Branch: req.Branch}, nil
}

// prTitle builds a conventional-commit-style title from the request description.
func prTitle(description string) string {
	d := strings.TrimSpace(strings.SplitN(description, "\n", 2)[0])
	if d == "" {
		d = "autopatch fix"
	}
	if len(d) > 72 {
		d = d[:72]
	}
	return "fix: " + d
}

// prBody builds a PR body from the autopatch result (diagnosis, diff stat,
// validation outcomes) so reviewers see the evidence behind the change.
func prBody(result Result) string {
	var b strings.Builder
	b.WriteString("Automated fix proposed by Prizm autopatch.\n\n")
	if result.Diagnosis != "" {
		b.WriteString("## Diagnosis\n\n" + result.Diagnosis + "\n\n")
	}
	if result.DiffStat != "" {
		b.WriteString("## Changes\n\n```\n" + result.DiffStat + "\n```\n\n")
	}
	if len(result.ValidationResults) > 0 {
		b.WriteString("## Validation\n\n")
		for _, vr := range result.ValidationResults {
			b.WriteString(fmt.Sprintf("- %s: %s (exit %d)\n", vr.Profile, vr.Status, vr.ExitCode))
		}
		b.WriteString("\n")
	}
	b.WriteString("🤖 Generated by Prizm autopatch\n")
	return b.String()
}

// maybeOpenPR opens a PR for a validated patch when the service is in "pr" mode.
// PR failure does not discard the validated patch — the result keeps its proposed
// status and records the error so the human still has the patch artifact.
func (s *Service) maybeOpenPR(ctx context.Context, cfg Config, req Request, taskID, worktree string, result *Result) {
	if cfg.Mode != "pr" || cfg.PROpener == nil {
		return
	}
	pr, err := cfg.PROpener.OpenPR(ctx, PRRequest{
		Worktree:   worktree,
		Branch:     "autopatch/" + safeID(taskID),
		Title:      prTitle(req.Description),
		Body:       prBody(*result),
		BaseBranch: cfg.BaseBranch,
	})
	result.Branch = pr.Branch
	if err != nil {
		result.Error = firstNonEmpty(result.Error, "pr creation failed: "+err.Error())
		return
	}
	result.Status = StatusPROpened
	result.PRURL = pr.URL
}
