package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	cfgpkg "github.com/emaharmony/prizm/internal/config"
	"github.com/emaharmony/prizm/internal/orchestrator"
	"gopkg.in/yaml.v3"
)

// cmd_config_setup.go implements `prizm config import` (OpenClaw JSON → Prizm YAML)
// and `prizm config wizard` (interactive setup). Both emit a minimal prizm.yaml —
// LoadConfig overlays it onto DefaultConfig, so unset fields get sensible defaults.

// exportConfig is a curated, omitempty view of the config we generate, so the YAML
// is tidy (only what the user set) rather than every default field.
type exportConfig struct {
	Prizm       exportPrizm        `yaml:"prizm"`
	Agents      []exportAgent      `yaml:"agents"`
	Remembrance *exportRemembrance `yaml:"remembrance,omitempty"`
}

type exportPrizm struct {
	InstanceID string `yaml:"instance_id,omitempty"`
	Workspace  string `yaml:"workspace,omitempty"`
	NATSURL    string `yaml:"nats_url,omitempty"`
}

type exportAgent struct {
	ID       string   `yaml:"id"`
	Role     string   `yaml:"role,omitempty"`
	Provider string   `yaml:"provider"`
	Model    string   `yaml:"model"`
	Primary  bool     `yaml:"primary,omitempty"`
	Context  []string `yaml:"context,omitempty"`
}

type exportRemembrance struct {
	Enabled bool   `yaml:"enabled"`
	URL     string `yaml:"url,omitempty"`
}

// marshalExport renders the export config as YAML with a header comment.
func marshalExport(ec *exportConfig) ([]byte, error) {
	data, err := yaml.Marshal(ec)
	if err != nil {
		return nil, err
	}
	header := "# Generated by `prizm config`. Unset fields fall back to built-in defaults.\n# Validate with: prizm config --config <this file>\n\n"
	return append([]byte(header), data...), nil
}

// sanitizeAgentID lowercases and strips a name to the agent-ID charset
// ([a-z0-9][a-z0-9-]*), so imported provider names are valid agent IDs.
func sanitizeAgentID(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	s := strings.Trim(b.String(), "-")
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		s = "agent-" + s
	}
	return s
}

// openClawToExport maps an OpenClaw JSON model catalog to a Prizm export config:
// one agent per provider (using the provider's first model), the first marked
// primary. Providers with no models are skipped.
func openClawToExport(data []byte) (*exportConfig, error) {
	var oc cfgpkg.OpenClawConfig
	if err := json.Unmarshal(data, &oc); err != nil {
		return nil, fmt.Errorf("parse OpenClaw JSON: %w", err)
	}
	names := make([]string, 0, len(oc.Models.Providers))
	for name := range oc.Models.Providers {
		names = append(names, name)
	}
	sort.Strings(names) // deterministic output

	ec := &exportConfig{
		Prizm:       exportPrizm{InstanceID: "prizm"},
		Remembrance: &exportRemembrance{Enabled: false},
	}
	for _, name := range names {
		pc := oc.Models.Providers[name]
		if len(pc.Models) == 0 {
			continue
		}
		provider := pc.API
		if provider == "" {
			provider = name
		}
		ec.Agents = append(ec.Agents, exportAgent{
			ID:       sanitizeAgentID(name),
			Role:     "assistant",
			Provider: provider,
			Model:    pc.Models[0].ID,
			Primary:  len(ec.Agents) == 0,
			Context:  []string{"soul", "user"},
		})
	}
	if len(ec.Agents) == 0 {
		return nil, fmt.Errorf("no providers with models found in OpenClaw JSON")
	}
	return ec, nil
}

// validateExport confirms the generated YAML loads and validates as a real Prizm
// config (LoadConfigFromBytes runs the same validation `prizm serve` does).
func validateExport(yamlData []byte) error {
	_, err := orchestrator.LoadConfigFromBytes(yamlData)
	return err
}

// writeConfigOutput writes YAML to path (or stdout when path is ""), refusing to
// clobber an existing file unless force is set.
func writeConfigOutput(path string, data []byte, force bool) error {
	if path == "" {
		_, err := os.Stdout.Write(data)
		return err
	}
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", path)
		}
	}
	return os.WriteFile(path, data, 0o644)
}

// runConfigImport implements `prizm config import <openclaw.json>`.
func runConfigImport(args []string) {
	fs := flag.NewFlagSet("config import", flag.ExitOnError)
	out := fs.String("out", "", "Write YAML to this file (default: stdout)")
	force := fs.Bool("force", false, "Overwrite an existing --out file")
	var src string
	rest := args
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		src = args[0]
		rest = args[1:]
	}
	fs.Parse(rest)
	if src == "" {
		src = cfgpkg.FindOpenClawConfig("") // fall back to the default OpenClaw location
	}
	data, err := os.ReadFile(src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ read OpenClaw JSON: %v\n", err)
		os.Exit(1)
	}
	ec, err := openClawToExport(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ %v\n", err)
		os.Exit(1)
	}
	yamlData, err := marshalExport(ec)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ marshal: %v\n", err)
		os.Exit(1)
	}
	if verr := validateExport(yamlData); verr != nil {
		fmt.Fprintf(os.Stderr, "❌ generated config failed validation: %v\n", verr)
		os.Exit(1)
	}
	if err := writeConfigOutput(*out, yamlData, *force); err != nil {
		fmt.Fprintf(os.Stderr, "❌ %v\n", err)
		os.Exit(1)
	}
	if *out != "" {
		fmt.Printf("✅ imported %d agent(s) from %s → %s\n", len(ec.Agents), src, *out)
	}
}

// wizardAnswers holds the values collected by the interactive wizard. Kept
// separate from assembly so wizardBuild is a pure, testable function.
type wizardAnswers struct {
	InstanceID  string
	Workspace   string
	AgentID     string
	Provider    string
	Model       string
	Remembrance bool
	// Agents, when non-empty (e.g. seeded from OpenClaw), overrides the single
	// Provider/Model/AgentID agent above.
	Agents []exportAgent
}

// defaultModelFor suggests a sensible default model per provider for the wizard.
func defaultModelFor(provider string) string {
	switch strings.ToLower(provider) {
	case "openai":
		return "gpt-4o"
	case "anthropic":
		return "claude-sonnet-4-6"
	case "gemini":
		return "gemini-2.0-flash"
	case "ollama":
		return "llama3.1"
	default:
		return ""
	}
}

// wizardBuild assembles an exportConfig from collected answers (pure, testable).
func wizardBuild(a wizardAnswers) *exportConfig {
	ec := &exportConfig{
		Prizm:       exportPrizm{InstanceID: a.InstanceID, Workspace: a.Workspace},
		Remembrance: &exportRemembrance{Enabled: a.Remembrance},
	}
	if len(a.Agents) > 0 {
		ec.Agents = a.Agents
		hasPrimary := false
		for i := range ec.Agents {
			if ec.Agents[i].Primary {
				hasPrimary = true
				break
			}
		}
		if !hasPrimary {
			ec.Agents[0].Primary = true
		}
		return ec
	}
	id := a.AgentID
	if id == "" {
		id = sanitizeAgentID(a.Provider)
	}
	ec.Agents = []exportAgent{{
		ID:       id,
		Role:     "assistant",
		Provider: a.Provider,
		Model:    a.Model,
		Primary:  true,
		Context:  []string{"soul", "user"},
	}}
	return ec
}

// prompt reads one line from r, showing a question and default; returns def on
// blank input or EOF.
func prompt(r *bufio.Reader, w io.Writer, question, def string) string {
	if def != "" {
		fmt.Fprintf(w, "%s [%s]: ", question, def)
	} else {
		fmt.Fprintf(w, "%s: ", question)
	}
	line, err := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" || err != nil {
		return def
	}
	return line
}

func promptYesNo(r *bufio.Reader, w io.Writer, question string, def bool) bool {
	d := "y/N"
	if def {
		d = "Y/n"
	}
	ans := strings.ToLower(prompt(r, w, question+" ("+d+")", ""))
	if ans == "" {
		return def
	}
	return ans == "y" || ans == "yes"
}

// runConfigWizard implements `prizm config wizard`.
func runConfigWizard(args []string) {
	fs := flag.NewFlagSet("config wizard", flag.ExitOnError)
	out := fs.String("out", "prizm.yaml", "Write the generated config to this file")
	force := fs.Bool("force", false, "Overwrite an existing --out file")
	fromOpenClaw := fs.String("from-openclaw", "", "Seed agents from an OpenClaw JSON file")
	fs.Parse(args)

	r := bufio.NewReader(os.Stdin)
	w := os.Stdout
	fmt.Fprintln(w, "🔮 Prizm config wizard — press Enter to accept the [default].")
	fmt.Fprintln(w)

	ans := wizardAnswers{}
	ans.InstanceID = prompt(r, w, "Instance ID", "prizm")
	cwd, _ := os.Getwd()
	ans.Workspace = prompt(r, w, "Workspace path", cwd)

	if *fromOpenClaw != "" {
		data, err := os.ReadFile(*fromOpenClaw)
		if err != nil {
			fmt.Fprintf(os.Stderr, "❌ read OpenClaw JSON: %v\n", err)
			os.Exit(1)
		}
		seed, err := openClawToExport(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "❌ %v\n", err)
			os.Exit(1)
		}
		ans.Agents = seed.Agents
		fmt.Fprintf(w, "  → seeded %d agent(s) from %s\n", len(ans.Agents), *fromOpenClaw)
	} else {
		ans.Provider = strings.ToLower(prompt(r, w, "Primary provider (ollama/openai/anthropic/gemini)", "ollama"))
		ans.Model = prompt(r, w, "Model", defaultModelFor(ans.Provider))
		ans.AgentID = prompt(r, w, "Agent ID", sanitizeAgentID(ans.Provider))
	}
	ans.Remembrance = promptYesNo(r, w, "Enable Remembrance (long-term memory)?", false)

	ec := wizardBuild(ans)
	yamlData, err := marshalExport(ec)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ marshal: %v\n", err)
		os.Exit(1)
	}
	if verr := validateExport(yamlData); verr != nil {
		fmt.Fprintf(os.Stderr, "❌ generated config failed validation: %v\n", verr)
		os.Exit(1)
	}
	if err := writeConfigOutput(*out, yamlData, *force); err != nil {
		fmt.Fprintf(os.Stderr, "❌ %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(w, "\n✅ wrote %s (%d agent(s)). Validate anytime with: prizm config --config %s\n", *out, len(ec.Agents), *out)
}
