package agentns

import "testing"

func TestNamespaceEventType(t *testing.T) {
	ns := New("lumi")
	tests := []struct {
		suffix string
		want   string
	}{
		{"agent.started", "lumi.agent.started"},
		{"tool.completed", "lumi.tool.completed"},
		{"llm.requested", "lumi.llm.requested"},
		{"channel.sent", "lumi.channel.sent"},
	}

	for _, tt := range tests {
		got := ns.EventType(tt.suffix)
		if got != tt.want {
			t.Errorf("EventType(%q) = %q, want %q", tt.suffix, got, tt.want)
		}
	}
}

func TestNamespaceConvenienceMethods(t *testing.T) {
	ns := New("mango")

	if ns.AgentStarted() != "mango.agent.started" {
		t.Errorf("AgentStarted() = %q, want %q", ns.AgentStarted(), "mango.agent.started")
	}
	if ns.AgentOutput() != "mango.agent.output" {
		t.Errorf("AgentOutput() = %q, want %q", ns.AgentOutput(), "mango.agent.output")
	}
	if ns.AgentCompleted() != "mango.agent.completed" {
		t.Errorf("AgentCompleted() = %q, want %q", ns.AgentCompleted(), "mango.agent.completed")
	}
	if ns.AgentFailed() != "mango.agent.failed" {
		t.Errorf("AgentFailed() = %q, want %q", ns.AgentFailed(), "mango.agent.failed")
	}
	if ns.LLMRequested() != "mango.llm.requested" {
		t.Errorf("LLMRequested() = %q, want %q", ns.LLMRequested(), "mango.llm.requested")
	}
	if ns.LLMCompleted() != "mango.llm.completed" {
		t.Errorf("LLMCompleted() = %q, want %q", ns.LLMCompleted(), "mango.llm.completed")
	}
	if ns.ToolRequested() != "mango.tool.requested" {
		t.Errorf("ToolRequested() = %q, want %q", ns.ToolRequested(), "mango.tool.requested")
	}
	if ns.ToolCompleted() != "mango.tool.completed" {
		t.Errorf("ToolCompleted() = %q, want %q", ns.ToolCompleted(), "mango.tool.completed")
	}
	if ns.ContextInjected() != "mango.context.injected" {
		t.Errorf("ContextInjected() = %q, want %q", ns.ContextInjected(), "mango.context.injected")
	}
	if ns.ChannelSent() != "mango.channel.sent" {
		t.Errorf("ChannelSent() = %q, want %q", ns.ChannelSent(), "mango.channel.sent")
	}
}

func TestAutoGeneratedNamespace(t *testing.T) {
	ns := New("prizm1")
	if ns.AgentStarted() != "prizm1.agent.started" {
		t.Errorf("Auto-generated: AgentStarted() = %q, want %q", ns.AgentStarted(), "prizm1.agent.started")
	}

	ns2 := New("prizm2")
	if ns2.AgentStarted() != "prizm2.agent.started" {
		t.Errorf("Auto-generated: AgentStarted() = %q, want %q", ns2.AgentStarted(), "prizm2.agent.started")
	}
}

func TestAutoGenerateID(t *testing.T) {
	tests := []struct {
		counter int
		want    string
	}{
		{1, "prizm1"},
		{2, "prizm2"},
		{10, "prizm10"},
	}
	for _, tt := range tests {
		got := AutoGenerateID(tt.counter)
		if got != tt.want {
			t.Errorf("AutoGenerateID(%d) = %q, want %q", tt.counter, got, tt.want)
		}
	}
}

func TestIsAgentEvent(t *testing.T) {
	tests := []struct {
		eventType string
		agentID   string
		want      bool
	}{
		{"lumi.agent.started", "lumi", true},
		{"lumi.tool.completed", "lumi", true},
		{"mango.agent.started", "lumi", false},
		{"prizm.cost.tracked", "lumi", false},
		{"prizm1.agent.started", "prizm1", true},
	}

	for _, tt := range tests {
		got := IsAgentEvent(tt.eventType, tt.agentID)
		if got != tt.want {
			t.Errorf("IsAgentEvent(%q, %q) = %v, want %v", tt.eventType, tt.agentID, got, tt.want)
		}
	}
}

func TestExtractAgentID(t *testing.T) {
	tests := []struct {
		eventType string
		want      string
	}{
		{"lumi.agent.started", "lumi"},
		{"mango.tool.completed", "mango"},
		{"prizm1.agent.output", "prizm1"},
		{"prizm.cost.tracked", ""}, // system event → no agent
		{"support-bot.channel.sent", "support-bot"},
	}

	for _, tt := range tests {
		got := ExtractAgentID(tt.eventType)
		if got != tt.want {
			t.Errorf("ExtractAgentID(%q) = %q, want %q", tt.eventType, got, tt.want)
		}
	}
}

func TestExtractEventSuffix(t *testing.T) {
	tests := []struct {
		eventType string
		want      string
	}{
		{"lumi.agent.started", "agent.started"},
		{"mango.tool.completed", "tool.completed"},
		{"prizm.cost.tracked", "cost.tracked"},
	}

	for _, tt := range tests {
		got := ExtractEventSuffix(tt.eventType)
		if got != tt.want {
			t.Errorf("ExtractEventSuffix(%q) = %q, want %q", tt.eventType, got, tt.want)
		}
	}
}

func TestAllAgentEventTypes(t *testing.T) {
	types := AllAgentEventTypes()
	if len(types) != 10 {
		t.Errorf("expected 10 event types, got %d", len(types))
	}

	// Verify each type has two parts (suffix.event)
	for _, et := range types {
		parts := splitAt(et, ".")
		if len(parts) < 2 {
			t.Errorf("event type %q doesn't have namespace separator", et)
		}
	}
}

// Helper to avoid importing strings just for the test.
func splitAt(s, sep string) []string {
	for i := 0; i < len(s)-len(sep)+1; i++ {
		if s[i:i+len(sep)] == sep {
			return []string{s[:i], s[i+len(sep):]}
		}
	}
	return []string{s}
}
