# Prizm Quality Report Script

$ReportPath = "QUALITY.md"
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

Write-Host "Gathering quality metrics..."

# 1. Go Metrics
# NOTE: test-file/test counts are scoped to git-tracked files (not a filesystem
# recursive scan) so vendored dependency sources under .tmp/gomodcache, venvs,
# etc. are never counted. A prior version of this script used
# Get-ChildItem -Recurse, which silently included every *_test.go under
# .tmp/gomodcache and inflated the reported count by roughly 5x.
$GoPackages = (go list ./... | Measure-Object).Count
$GoTestFiles = (git ls-files '*_test.go' | Measure-Object).Count
$GoTests = (go test -list . ./... | Select-String "^Test" | Measure-Object).Count
$GoBenchmarks = (git ls-files '*_test.go' | ForEach-Object { Select-String -Path $_ -Pattern '^func Benchmark[A-Za-z0-9_]+' } | Measure-Object).Count

# 2. Integration Tests
$IntegrationTests = (go test -list . ./internal/integration | Select-String "^Test" | Measure-Object).Count

# 3. Python Metrics (Remembrance + SDK) — counts test *functions* across all
# git-tracked test files, not just file counts in one directory.
$PythonTestFiles = git ls-files '*.py' | Where-Object { $_ -match '(^|/)tests?/.*\.py$' -or $_ -match '(^|/)test_[^/]+\.py$' }
$PythonTests = 0
foreach ($f in $PythonTestFiles) {
    $matches = Select-String -Path $f -Pattern '^\s*(async\s+)?def test_' -AllMatches
    if ($matches) { $PythonTests += $matches.Matches.Count }
}

# 4. Build Status
$BuildStatus = "Unknown"
go build ./...
if ($LASTEXITCODE -eq 0) { $BuildStatus = "Passing" } else { $BuildStatus = "Failing" }

# 5. Lint Status
$LintStatus = "Unknown"
go vet ./...
if ($LASTEXITCODE -eq 0) { $LintStatus = "Passing" } else { $LintStatus = "Failing" }

# 6. Git Cleanliness
$GitClean = "Clean"
$GitStatus = git status --porcelain
if ($GitStatus) { $GitClean = "Dirty" }

# Generate QUALITY.md
$Content = @"
# Prizm Repository Quality Report

Last verified: $Now

## Metrics
- **Go packages:** $GoPackages
- **Go test files:** $GoTestFiles
- **Go tests:** $GoTests
- **Go benchmarks:** $GoBenchmarks
- **Integration tests:** $IntegrationTests
- **Python tests (Remembrance + SDK):** $PythonTests
- **Build status:** $BuildStatus
- **Lint status (vet):** $LintStatus
- **Git status:** $GitClean

## Feature Stability Summary
- **Stable:** Workflow Engine, Event Bus, Policy Engine, Approval Gates, Validation Gates, Tool Registry, Providers.
- **Preview:** API, Dashboard, Scheduler, Discord Adapter, Worktree Mutation.
- **Experimental:** Remembrance, MCP, Cross-Prizm, Sub-agents, Autopatch, Free Mode / Shell Tool (master-user-only, opt-in).

## CI & Verification
- **Supported Platforms:** Linux (full suite), Windows (basic subset: safety, config, run + CLI doctor smoke test).
- **Race Testing:** Enabled for ``bus``, ``event``, ``run``, ``workflow``, ``safety``, ``policy``, ``agent``, ``orchestrator``, ``task`` (see ``.github/workflows/ci.yml``).
- **Known Limitations:** See [Stability Matrix](./docs/reference/stability-matrix.md).

---
*This report is auto-generated by ``scripts/quality-report.ps1``.*
"@

$Content | Out-File -FilePath $ReportPath -Encoding utf8
Write-Host "Quality report generated: $ReportPath"
