package router

import (
	"testing"

	"github.com/emaharmony/prizm/internal/agent"
	"github.com/emaharmony/prizm/internal/orchestrator"
)

func TestRouteDirect(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "lumi", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})
	reg.Register(&agent.Agent{Name: "mango", Role: "coder", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "code", Description: "code"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Primary: true},
			{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud"},
		},
	}

	r := New(reg, cfg)

	result := r.Route("Lumi, fix this bug")
	if result.AgentID != "lumi" {
		t.Errorf("expected agent 'lumi', got %q", result.AgentID)
	}
	if result.Method != "direct" {
		t.Errorf("expected method 'direct', got %q", result.Method)
	}
	if result.CleanedContent != "fix this bug" {
		t.Errorf("expected 'fix this bug', got %q", result.CleanedContent)
	}
}

func TestRouteDirectWithoutComma(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "mango", Role: "coder", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "code", Description: "code"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud"},
		},
	}

	r := New(reg, cfg)

	result := r.Route("Mango write tests")
	if result.AgentID != "mango" {
		t.Errorf("expected agent 'mango', got %q", result.AgentID)
	}
	if result.Method != "direct" {
		t.Errorf("expected method 'direct', got %q", result.Method)
	}
}

func TestRouteMention(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "lumi", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})
	reg.Register(&agent.Agent{Name: "mango", Role: "coder", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "code", Description: "code"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Primary: true},
			{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud"},
		},
	}

	r := New(reg, cfg)

	result := r.Route("@Mango write tests")
	if result.AgentID != "mango" {
		t.Errorf("expected agent 'mango', got %q", result.AgentID)
	}
	if result.Method != "mention" {
		t.Errorf("expected method 'mention', got %q", result.Method)
	}
	if result.CleanedContent != "write tests" {
		t.Errorf("expected 'write tests', got %q", result.CleanedContent)
	}
}

func TestRoutePrimary(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "lumi", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})
	reg.Register(&agent.Agent{Name: "mango", Role: "coder", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "code", Description: "code"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Primary: true},
			{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud"},
		},
	}

	r := New(reg, cfg)

	// No address → primary agent
	result := r.Route("what's the status?")
	if result.AgentID != "lumi" {
		t.Errorf("expected primary 'lumi', got %q", result.AgentID)
	}
	if result.Method != "primary" {
		t.Errorf("expected method 'primary', got %q", result.Method)
	}
}

func TestRoutePrimaryFallback(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "first", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})
	reg.Register(&agent.Agent{Name: "second", Role: "coder", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "code", Description: "code"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "first", Role: "lead", Model: "glm-5.1:cloud"},
			{ID: "second", Role: "coder", Model: "deepseek-v4-pro:cloud"},
		},
	}

	r := New(reg, cfg)

	// No primary set → first agent
	result := r.Route("hello")
	if result.AgentID != "first" {
		t.Errorf("expected first agent as fallback, got %q", result.AgentID)
	}
}

func TestRouteAutoGeneratedIDs(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "prizm1", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "prizm1", Role: "lead", Model: "glm-5.1:cloud", Primary: true},
		},
	}

	r := New(reg, cfg)

	result := r.Route("prizm1, check the logs")
	if result.AgentID != "prizm1" {
		t.Errorf("expected agent 'prizm1', got %q", result.AgentID)
	}
	if result.Method != "direct" {
		t.Errorf("expected method 'direct', got %q", result.Method)
	}
}

func TestRouteCaseInsensitive(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "lumi", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Primary: true},
		},
	}

	r := New(reg, cfg)

	tests := []struct {
		input string
		want  string
	}{
		{"Lumi, hello", "lumi"},
		{"LUMI check this", "lumi"},
		{"lumi what's up", "lumi"},
		{"@LUMI help", "lumi"},
	}

	for _, tt := range tests {
		result := r.Route(tt.input)
		if result.AgentID != tt.want {
			t.Errorf("Route(%q): expected %q, got %q", tt.input, tt.want, result.AgentID)
		}
	}
}

func TestRouteDirectAddressBeatsMention(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "lumi", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})
	reg.Register(&agent.Agent{Name: "mango", Role: "coder", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "code", Description: "code"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Primary: true},
			{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud"},
		},
	}

	r := New(reg, cfg)

	// "Lumi, what about @Mango's code?" should route to Lumi (direct address)
	// not Mango (@mention), because direct address takes priority
	result := r.Route("Lumi, what about @Mango's code?")
	if result.AgentID != "lumi" {
		t.Errorf("direct address should beat @mention: expected 'lumi', got %q", result.AgentID)
	}
	if result.Method != "direct" {
		t.Errorf("expected method 'direct', got %q", result.Method)
	}
}

func TestRouteUnknownAddress(t *testing.T) {
	reg := agent.NewRegistry()
	reg.Register(&agent.Agent{Name: "lumi", Role: "lead", Version: "1.0.0", Capabilities: []agent.AgentCapability{{Action: "plan", Description: "plan"}}})

	cfg := &orchestrator.Config{
		Agents: []orchestrator.AgentConfig{
			{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Primary: true},
		},
	}

	r := New(reg, cfg)

	// Unknown agent name → primary fallback
	result := r.Route("UnknownAgent, do something")
	if result.Method != "primary" {
		t.Errorf("expected 'primary' for unknown agent, got %q", result.Method)
	}
}
